# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: betsy

on:
  push:
    branches: 
      - master
  #release:
    #types: [created]
    #try

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          git config --global user.email "hellorosss@gmail.com"
          git config --global user.name "rsbear"
          cd package
          yarn 
          yarn version --patch
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        
          
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@rsbear'
      - name: Publish to NPM
        run: | 
          git config --global user.email "hellorosss@gmail.com"
          git config --global user.name "rsbear"
          cd package
          yarn publish --@rsbear:registry=https://registry.npmjs.org/ --access-public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      #publish to gpr
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@rsbear'
      - name: Publish to GitHub Package Registry
        run: |
          git config --global user.email "hellorosss@gmail.com"
          git config --global user.name "rsbear"
          cd package
          yarn publish --@rsbear:registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.gh_token}}
  
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   # if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - name: Publish to npm registry
  #       run: |
  #         git config --global user.email "hellorosss@gmail.com"
  #         git config --global user.name "rsbear"
  #         cd canvas
  #         ls -lah
  #         yarn publish --@rsbear:registry=https://registry.npmjs.org/ --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   # if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #     - name: Publish to GPR
  #       run: |
  #         git config --global user.email "hellorosss@gmail.com"
  #         git config --global user.name "rsbear"
  #         cd canvas
  #         yarn 
  #         yarn version --patch
  #         yarn build
  #         yarn publish --registry=https://npm.pkg.github.com/
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.gh_token}}